version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      dependencies:
        patterns:
          - '*'
        update-types: ['minor']
    schedule:
      interval: 'monthly'
