steps:
  # Build the new version of the bot
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/rusty-244803/prod:latest', '.']
    timeout: 600s

  # Push up the newest version once we are done pruning
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us.gcr.io/rusty-244803/prod:latest']

  # Complete the process by updating the container with the newest image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instances',
        'update-container',
        'rusty-prod',
        '--zone=us-east1-b',
        '--container-image=us.gcr.io/rusty-244803/prod:latest'
      ]
