steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=rustykey.json.enc
  - --plaintext-file=rustykey.json
  - --location=global
  - --keyring=RustyKeyRing
  - --key=rustykey

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us.gcr.io/rusty-244803/prod:latest', '.' ]
  timeout: 600s
images:
- 'us.gcr.io/rusty-244803/prod'
