steps:
# Decrypt the credentials in the repo before we deploy
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'kms',
        'decrypt',
        '--ciphertext-file=rustykey.json.enc',
        '--plaintext-file=rustykey.json',
        '--location=global',
        '--keyring=RustyKeyRing',
        '--key=rustykey'
      ]

# Build the new version of the bot
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us.gcr.io/rusty-244803/prod:latest', '.']
    timeout: 600s

# Push up the newest version once we are done pruning
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us.gcr.io/rusty-244803/prod:latest']
    
# Complete the process by updating the container with the newest image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instances',
        'update-container',
        'rusty-prod',
        '--zone=us-east1-b',
        '--container-image=us.gcr.io/rusty-244803/prod:latest'
      ]
