steps:
  # Build the new version of the bot
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/${PROJECT_ID}/${_REGISTRY_NAME}:${_REGISTRY_TAG}',
        '.'
      ]
    timeout: 600s

  # Push up the newest version once we are done pruning
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/${_REGISTRY_NAME}:${_REGISTRY_TAG}']

  # Complete the process by updating the container with the newest image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'compute',
        'instances',
        'update-container',
        '${_CONTAINER_NAME}',
        '--zone=${_ZONE}',
        '--container-image=gcr.io/${PROJECT_ID}/${_REGISTRY_NAME}:${_REGISTRY_TAG}'
      ]
