import type { ClientEvents } from 'discord.js';

export const CLIENT_EVENT_TYPES: readonly (keyof ClientEvents)[] = [
  'applicationCommandPermissionsUpdate',
  'cacheSweep',
  'channelCreate',
  'channelDelete',
  'channelPinsUpdate',
  'channelUpdate',
  'debug',
  'warn',
  'emojiCreate',
  'emojiDelete',
  'emojiUpdate',
  'error',
  'guildBanAdd',
  'guildBanRemove',
  'guildCreate',
  'guildDelete',
  'guildUnavailable',
  'guildIntegrationsUpdate',
  'guildMemberAdd',
  'guildMemberAvailable',
  'guildMemberRemove',
  'guildMembersChunk',
  'guildMemberUpdate',
  'guildUpdate',
  'inviteCreate',
  'inviteDelete',
  'messageCreate',
  'messageDelete',
  'messageReactionRemoveAll',
  'messageReactionRemoveEmoji',
  'messageDeleteBulk',
  'messageReactionAdd',
  'messageReactionRemove',
  'messageUpdate',
  'presenceUpdate',
  'ready',
  'invalidated',
  'roleCreate',
  'roleDelete',
  'roleUpdate',
  'threadCreate',
  'threadDelete',
  'threadListSync',
  'threadMemberUpdate',
  'threadMembersUpdate',
  'threadUpdate',
  'typingStart',
  'userUpdate',
  'voiceStateUpdate',
  'webhookUpdate',
  'interactionCreate',
  'shardDisconnect',
  'shardError',
  'shardReady',
  'shardReconnecting',
  'shardResume',
  'stageInstanceCreate',
  'stageInstanceUpdate',
  'stageInstanceDelete',
  'stickerCreate',
  'stickerDelete',
  'stickerUpdate',
  'guildScheduledEventCreate',
  'guildScheduledEventUpdate',
  'guildScheduledEventDelete',
  'guildScheduledEventUserAdd',
  'guildScheduledEventUserRemove'
];

export const RANDOM_ACTIVITY_CRON = '0 0 0 * * *';

export const DEFAULT_RANDOM_VOICE_CHANNEL_NAMES_CRON = '0 0 0 * * *';

/** Minimum number of minutes between changing the channel names */
export const CHANNEL_NAME_CHANGE_RATE_LIMIT = 10;

export const RUSTY_WEBSITE_URL = 'https://rusty.mr1upmachine.com/';
