name: Deploy

on:
  workflow_call:
    inputs:
      artifact-dir:
        type: string
      environment:
        required: true
        type: string
      vm-name:
        type: string
  workflow_dispatch:
    inputs:
      artifact-dir:
        type: string
      environment:
        required: true
        type: environment
      vm-name:
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images:
            gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ inputs.artifact-dir || inputs.environment }}
            # generate Docker tags based on the following events/attributes
          tags: |
            latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Restart VM
        run: gcloud compute instances reset ${{ inputs.vm-name || inputs.environment }} --zone=[ZONE]
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
