name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check if commit message is semantic version
        id: check_semantic_version
        run: |
          regex="^[0-9]+\.[0-9]+\.[0-9]+$"
          if [[ "${{ github.event.head_commit.message }}" =~ $regex ]]; then
            echo "is_semantic_version=true" >> $GITHUB_OUTPUT
          else
            echo "is_semantic_version=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      is_semantic_version: ${{ steps.check_semantic_version.outputs.is_semantic_version }}
  deploy:
    name: Deploy
    needs: check-commit-message
    if: needs.check-commit-message.outputs.is_semantic_version == true
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: prod
